version: "3.7"

services:
    postgres:
        image: postgres:14.3
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        expose:
            - "5432"
        volumes:
            - ./docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
        networks:
            - network

    backend:
        build: ./backend
        ports:
            - "${PORT}:${PORT}"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            DATABASE_URL: ${DATABASE_URL}
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - postgres
        env_file:
            - .env
        networks:
            - network
networks:
    network: {}

